name: flutter_group_project
description: A Flutter app for Craftique eCommerce
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase core packages
  firebase_database: ^10.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.9.3
  provider: ^6.0.0

  # UI and utility
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/paintings/
    - assets/images/ceramics/
    - assets/images/jewelry/
    - assets/images/clothing/
    - assets/images/miniature/
    - assets/images/craftique_logo.png
    - assets/images/craftique_logod.png