// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqs9dhMo_zxEM-dfY44ZY53vVFqclUCI',
    appId: '1:572715423929:web:5e98c522866b688dfbe368',
    messagingSenderId: '572715423929',
    projectId: 'flutter-group-project-3541f',
    authDomain: 'flutter-group-project-3541f.firebaseapp.com',
    storageBucket: 'flutter-group-project-3541f.firebasestorage.app',
    measurementId: 'G-K3HJX38H7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf-FNhd5nD2EZ787h9lj2afbk6ATZgY2Y',
    appId: '1:572715423929:android:a758932ec466f8bcfbe368',
    messagingSenderId: '572715423929',
    projectId: 'flutter-group-project-3541f',
    storageBucket: 'flutter-group-project-3541f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIhe1qi2GnN_-Pt_ISvuuLe4X6ra9zicQ',
    appId: '1:572715423929:ios:44e5e9fa39202b25fbe368',
    messagingSenderId: '572715423929',
    projectId: 'flutter-group-project-3541f',
    storageBucket: 'flutter-group-project-3541f.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIhe1qi2GnN_-Pt_ISvuuLe4X6ra9zicQ',
    appId: '1:572715423929:ios:44e5e9fa39202b25fbe368',
    messagingSenderId: '572715423929',
    projectId: 'flutter-group-project-3541f',
    storageBucket: 'flutter-group-project-3541f.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqs9dhMo_zxEM-dfY44ZY53vVFqclUCI',
    appId: '1:572715423929:web:035fe5509d2dadc6fbe368',
    messagingSenderId: '572715423929',
    projectId: 'flutter-group-project-3541f',
    authDomain: 'flutter-group-project-3541f.firebaseapp.com',
    storageBucket: 'flutter-group-project-3541f.firebasestorage.app',
    measurementId: 'G-L1FLXSXS30',
  );
}
